run:
  timeout: 20m
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly
  skip-dirs:
    - go/pkg  # remove third party mod lib from scanning
    - go/src  # remove third party mod lib from scanning
    - hostedtoolcache  # remove the mod caches from scanning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  print-linter-name: true
  sort-results: true
  uniq-by-line: false
  print-issued-lines: true

linters:
  disable-all: true
  fast: false
  enable:
    # A stricter replacement for gofmt.
    - gofumpt
    # Check for correctness of programs.
    - govet
    # Drop-in replacement of golint.
    - revive
