name: Common Workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

env:
  # The hostname used to communicate with the Redis service container
  REDIS_HOST: redis
  # The default Redis port
  REDIS_PORT: 6379

jobs:

  # golang static analysis checks
  go-static-analysis:
    uses: dell/common-github-actions/.github/workflows/go-static-analysis.yaml@main
    name: Golang Validation

  redis:
    name: Set up Redis
    runs-on: ubuntu-latest
    container: node:20
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  common:
    name: Quality Checks
    needs: redis
    uses: dell/common-github-actions/.github/workflows/go-common.yml@main
